logging.level.root=${LOG_LEVEL:WARN}
ogging.file.name=logs/eazystore-qa.log
spring.jpa.show-sql=${JPA_SHOW_URL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}
contact.phone=+91-1234567891
contact.email=qa@eazystore.com
contact.address=123 Main Street, London, UK